blank_issues_enabled: false
contact_links:
  - name: Youssef Land
    url: https://yoyomonem22.wixsite.com/youssefland
    about: This is the unforgettable Youssef Land, so that you will be happy ğŸ˜‰
    
